<?php

namespace AppBundle\Repository;

/**
 * CommandeBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
