<?php

namespace AppBundle\Repository;

/**
 * EcommerceConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcommerceConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
