<?php

namespace AppBundle\Repository;

// use Doctrine\ORM\EntityRepository;
// use Doctrine\ORM\QueryBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  // public function getProductWithCategory(array $categoryNames)
  // {
  //   $qb = $this->createQueryBuilder('p');

  //   // On fait une jointure avec l'entité Category avec pour alias « c »
  //   $qb
  //   ->join('p.categories', 'c')
  //   ->addSelect('c')
  //   ;

  //   // Puis on filtre sur le nom des catégories à l'aide d'un IN
  //   $qb->where($qb->expr()->in('c.name', $categoryNames));
  //   // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

  //   // Enfin, on retourne le résultat
  //   return $qb
  //   ->getQuery()
  //   ->getResult()
  //   ;
  // }

  public function findArray($array){
    $qb = $this->createQueryBuilder('u')
              ->Select('u')
              ->Where('u.id IN (:array)')
              ->setParameter('array', $array);
    return $qb->getQuery()->getResult();
  }
}
